--enable-features=VaapiVideoDecoder,VaapiIgnoreDriverChecks,Vulkan,DefaultANGLEVulkan,VulkanFromANGLE,UseOzonePlatform
--ozone-platform=x11
--ignore-gpu-blocklist
--enable-zero-copy
--enable-gpu-rasterization
--password-store=gnome
